### ISSUE TITLE
你好，管理员登录界面登录不上去。

### ISSUE THREAD

**Issue by ghost** [zhang0chao0/BookStore#1]
数据库也建立了，账号admin密码admin。登录时提示密码错误或未激活，JSP页面也没有看到有home.jsp（管理页面）。o(╥﹏╥)o 希望楼主解惑。

**Comment by zhang0chao0** [comment]
啊，好久没看了，管理员后台是可以用的，这个代码我是参考了 传智播客 的一个项目，网上可以搜到的，叫 网上商城系统吧 ，你可以找找看



1170826505@qq.com
 
发件人： 夏沫未泱ヾ
发送时间： 2018-05-20 17:42
收件人： zhang0chao0/BookStore
抄送： Subscribed
主题： [zhang0chao0/BookStore] 你好，管理员登录界面登录不上去。 (#1)
数据库也建立了，账号admin密码admin。登录时提示密码错误或未激活，JSP页面也没有看到有home.jsp（管理页面）。o(╥﹏╥)o 希望楼主解惑。

**Comment by ghost** [comment]
找到了，谢谢Thanks♪(･ω･)ﾉ
